<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-R6HH0JS3" failures="3" tests="4" name="Test" time="8.073" errors="0" timestamp="2023-12-26T00:59:18 IST">
  <testcase classname="api.testCases.UserTest2" name="testCreatUser" time="3.439">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testCases.UserTest2.testCreatUser(UserTest2.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testCreatUser -->
  <testcase classname="api.testCases.UserTest2" name="testgetUser" time="1.34">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testCases.UserTest2.testgetUser(UserTest2.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testgetUser -->
  <testcase classname="api.testCases.UserTest2" name="testupdateUser" time="1.428"/>
  <testcase classname="api.testCases.UserTest2" name="testdelUser" time="1.235">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testCases.UserTest2.testdelUser(UserTest2.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testdelUser -->
</testsuite> <!-- Test -->
